#from ibm_watsonx_ai.foundation_models import ModelInference
#from ibm_watsonx_ai.metanames import GenTextParamsMetaNames as GenParams
#from ibm_watsonx_ai.metanames import EmbedTextParamsMetaNames
#from ibm_watsonx_ai import Credentials
#from langchain_ibm import WatsonxLLM, WatsonxEmbeddings
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.vectorstores import Chroma
from langchain_community.document_loaders import PyPDFLoader
from langchain_classic.chains import RetrievalQA #Deprecated stfuff in langchain_classic
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_google_genai.llms import ChatGoogleGenerativeAI
import gradio as gr
# You can use this section to suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')

## LLM
#import os
#os.environ["GOOGLE_API_KEY"] = "..blah.."
def get_llm():
    '''
    model_id = 'ibm/granite-3-2-8b-instruct'
    parameters = {
        GenParams.MAX_NEW_TOKENS: 256,  # Specify the max tokens you want to generate
        GenParams.TEMPERATURE: 0.5, # This randomness or creativity of the model's responses
    }
    project_id = "skills-network"
    watsonx_llm = WatsonxLLM(
        model_id=model_id,
        url="https://us-south.ml.cloud.ibm.com",
        project_id=project_id,
        params=parameters,
    )
    '''
    llm = ChatGoogleGenerativeAI(
        model="gemini-2.5-flash-lite",
        temperature=0.7,
        max_tokens=2000,
        timeout=None,
        max_retries=2,
    )
    return llm #watsonx_llm

## Document loader
def document_loader(file):
    loader = PyPDFLoader(file.name)
    loaded_document = loader.load()
    print(f"{loaded_document=}")
    return loaded_document

## Text splitter
def text_splitter(data):
    text_splitter = RecursiveCharacterTextSplitter(
        chunk_size= 1000,
        chunk_overlap= 10,
        length_function= len,
    )
    chunks = text_splitter.split_documents(data)
    return chunks

## Embedding model
'''
def watsonx_embedding():
    embed_params = {
        EmbedTextParamsMetaNames.TRUNCATE_INPUT_TOKENS: 3,
        EmbedTextParamsMetaNames.RETURN_OPTIONS: {"input_text": True},
    }
    #SSHAH alternative can be HuggingFaceEmbedding (covered in reading, and may be used in next coding exercise)
    watsonx_embedding = WatsonxEmbeddings(
        model_id="slate-125m-english-rtrvr-v2", #"ibm/slate-125m-english-rtrvr",
        url="https://us-south.ml.cloud.ibm.com",
        project_id="skills-network",
        params=embed_params,
    )
    return watsonx_embedding
'''

## Vector db
def vector_database(chunks):
    #embedding_model = watsonx_embedding()
    embedding_model = HuggingFaceEmbeddings()
    vectordb = Chroma.from_documents(chunks, embedding_model)
    return vectordb

## Retriever
def retriever(file):
    splits = document_loader(file)
    chunks = text_splitter(splits)
    vectordb = vector_database(chunks)
    retriever = vectordb.as_retriever()
    return retriever

## QA Chain
def retriever_qa(file, query):
    llm = get_llm()
    retriever_obj = retriever(file)
    qa = RetrievalQA.from_chain_type(llm=llm, 
                                    chain_type="stuff", 
                                    retriever=retriever_obj,
                                    return_source_documents=False)
    response = qa.invoke(query)
    return response['result']

# Create Gradio interface
rag_application = gr.Interface(
    fn=retriever_qa,
    allow_flagging='auto',
    inputs=[
        gr.File(label="Upload PDF File", file_count="single", file_types=['.pdf'], type="filepath"),  # Drag and drop file upload
        gr.Textbox(label="Input Query", lines=2, placeholder="Type your question here...")
    ],
    outputs=gr.Textbox(label="Answer", lines=5),
    title="Q & A",
    description="Upload a PDF document and ask any question. The chatbot will try to answer using the provided document."
)

# Launch the app
rag_application.launch(server_name="127.0.0.1", server_port= 7860)
